Iter13
renatus-cartesius/metricserv pull request #13
Opened 2024-11-14 19:29 UTC by renatus-cartesius

2024-11-18 20:57 UTC, bulbetski reviewed
Всё в целом хорошо. 
Критическое замечание по поводу механизма миграций, остальные замечания минорные по обработке ошибок

2024-11-18 20:57 UTC, bulbetski commented on cmd/server/main.go
> +			);`,
Вместо инициализации таблицы в метриках стоит воспользоваться механизмом миграций. Например, погугли про goose.

2024-11-18 20:57 UTC, bulbetski commented on cmd/server/main.go
> +			)
Нет завершения мэйна в случае неудачной миграции. Надо тут фаталиться

2024-11-18 20:57 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		delta := *metric.Delta
возможно разыменование нулевого указателя. Всегда перед этим надо проверять на delta != nil.

2024-11-18 20:57 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +			*metric.Delta = actualDelta
Delta может быть nil, это вызовет панику. Можно сделать так

```
if metric.Delta == nil {
    metric.Delta = new(int64) // Allocate memory for Delta if it's nil
}
*metric.Delta = actualDelta
```

2024-11-18 20:57 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +}
можно добавить логи, ну и соотвественно возвращать из пинга ошибку, а не ок

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +	return true
можно проверить, инициализирована ли мапа из MemStorage

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +		log.Fatalln(err)
Фаталимся только в мэйне

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +		return false
увидел лог, но все равно лучше возвращать ошибку и логировать максимально высоко по стеку вызовов

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +		)
стоит вынести лог выше по стеку вызовов

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +	row.Scan(&count)
надо обрабатывать ошибку сканирования

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +func (pgs *PGStorage) Ping(ctx context.Context) bool {
Комментарий ко всему пакету. Методы должны возвращать ошибки. Ошибки логировать максимально высоко по стеку вызовов

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +	// TODO: remove this workaround
тудушку будешь делать?

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +	row.Scan(&value)
надо обработать ошибку

2024-11-18 20:57 UTC, bulbetski commented on internal/storage/storage.go
> +	switch mtype {
можно написать еще дефолтный кейс для надежности

2024-11-19 22:17 UTC, renatus-cartesius commented on internal/storage/storage.go
> +	// TODO: remove this workaround
Пока хз как) Если только в будущем структуры метрик привести к sql.Scanner и driver.Valuer

2024-11-20 22:06 UTC, bulbetski reviewed
критическую тему с миграциями исправил, отлично. Остались небольшие моменты с потенциальным разыменованием нулевого указателя и пропущенной обработкой ошибок

2024-11-20 22:06 UTC, bulbetski commented on cmd/server/migrations/00001_add_metrics_table.sql
> +SELECT 'down SQL query';
Не должно ли тут быть DROP TABLE?

2024-11-20 22:06 UTC, bulbetski commented on cmd/server/main.go
> +	var s storage.Storager
классно, что сделал, хорошее изменение

2024-11-20 22:06 UTC, bulbetski commented on internal/storage/storage_test.go
> +	metrics, _ := storage.ListAll(context.Background())
обработать ошибку

2024-11-22 08:48 UTC, bulbetski requested changes
Норм. Но надо еще поправить

2024-11-22 08:48 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		)
тут должен быть еще и return. Можно так же возвращать кастомную not found ошибку из GetValue и её отдельно хэндлить её через errors.Is(err, *your_error*)

2024-11-22 08:48 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +	}
то же самое

2024-11-22 08:48 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +			)
тоже нужен return

2024-11-22 08:48 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +				)
return

2024-11-22 08:48 UTC, bulbetski commented on internal/storage/storage.go
> +		return
вкусовщина, но я бы не использовал именованные return'ы

2024-11-22 08:48 UTC, bulbetski commented on internal/storage/storage.go
>  	return
лучше в каждом из кейсов делать return fmt.Sprintf и nil. тогда каждый из кейсов можно будет расширять независимо друг от друга. И именованные параметры только путают, потому что пустой return как правило означает, что у функции нет возвращаемых параметров

2024-11-22 17:00 UTC, renatus-cartesius commented on internal/server/handlers/handlers.go
> +		)
У меня проверка наличия метрики в хранилище чуть выше происходит

2024-11-22 19:07 UTC, bulbetski commented
Молодец, всё хорошо исправил, осталось 2 микрокоммента про обработку ошибок row.Scan()

2024-11-22 19:07 UTC, bulbetski approved these changes

2024-11-24 23:44 UTC, merged