chore: dummy
renatus-cartesius/metricserv pull request #15
Opened 2024-11-26 20:46 UTC by renatus-cartesius

2024-12-03 01:54 UTC, bulbetski requested changes
Решение будет работать, но все обезопаситься от возможных блокировок и паник. Так же полезно будет создать отдельную библиотеку воркер пула (пригодится дальше в выпускных проектах и дальнейшей работе)

2024-12-03 01:54 UTC, bulbetski commented on internal/agent/agent.go
> +	a.reportWg.Done()
Вот здесь defer явно вызывается в конце функции, что не очень хорошо, потому что этот defer может не выполниться в случае ошибки или паники (конкретно в этом месте мб как бы и ок будет, но если говорить глобально, то это плохая практика).
Стоит стараться писать wg.Done() в том же месте, где у тебя создается горутина и происходит wg.Add().

В твоем случае что-то такое
```
go func(workerID int) {
			defer a.reportWg.Done()
			a.StartReportWorker(workerID)
		}(i)
```

2024-12-03 01:54 UTC, bulbetski commented on internal/agent/agent.go
> +	reportWg       *sync.WaitGroup
Не очень хорошо, что воркер пул является частью агента. Подумай в сторону создания независимого универсального пакета для создания воркер пула. Так мы сможем соблюсти принцип единственной ответственности, облегчить тестирование и в дальнейшем переиспользовать код нашего воркер пула.

2024-12-03 01:54 UTC, bulbetski commented on internal/agent/agent.go
> +			close(a.reportCh)
Канал всегда нужно закрывать со стороны отправителя, потому что может случиться паника, если горутины будут писать в уже закрытый канал. 
После закрытия канала нам нужно подождать, что все горутины отработают. Так же во все горутины надо отправить сигнал <-a.exitCh, чтобы мы не пытались отправлять данные

2024-12-03 01:54 UTC, bulbetski commented on internal/agent/agent.go
> +	gzWriter.Flush()
не обрабатываем ошибку

2024-12-03 01:54 UTC, bulbetski commented on internal/agent/agent.go
> +	resp, err := a.Send(metric, updateURI)
Если мы всегда передаем внутрь константу, то как будто можно вообще ничего не передавать и использовать эту константу внутри

2024-12-03 01:54 UTC, bulbetski commented on internal/agent/agent.go
> +	a.reportCh <- &monitor.RuntimeMetric{Name: "TotalMemory", Value: fmt.Sprintf("%v", float64(v.Total))}
Тут мы отправляем данные в небуферизованный канал, от чего будет происходить блокировка в случае, когда другая горутина еще не успела обработать входящие метрики. По сути метод Report ждет, пока воркеры освободят канал, и не успевает завершить работу до следующего вызова.

Как решение, сделать reportCh буферизованным, чтобы сделать отправку НЕблокирующей до момента заполнения буфера

2024-12-03 14:09 UTC, renatus-cartesius commented on internal/agent/agent.go
> +	resp, err := a.Send(metric, updateURI)
Тогда бы пришлось делать два метода вместо одного: SendUpdates и SendUpdate

2024-12-05 20:50 UTC, renatus-cartesius commented on internal/agent/agent.go
> +			close(a.reportCh)
Как быть, если у меня отправитель a.Report() вызывается с периодичностью и в таком случае(если отправитель у нас закрывает канал) отправитель закроет канал после первого вызова?

2024-12-05 20:51 UTC, renatus-cartesius commented on internal/agent/agent.go
> +			close(a.reportCh)
Тогда видимо надо как-то с контекстом работать я думаю

2024-12-06 01:20 UTC, bulbetski commented on pkg/workerpool/workerpool.go
> +func (p *Pool) Listen(workers int, do func()) {
воркеры в твоем пуле должны завершаться в случае ctx.Done()

2024-12-06 01:22 UTC, bulbetski commented on internal/agent/agent.go
> +			close(a.reportCh)
Вообще схема в целом такая, не знаю ответит ли это на твой вопрос.
Какая-то сущность отправляет джобы (как угодно, с какой угодной периодичностью) в канал, этот канал слушается твоим воркер пулом. 

Канал надо закрыть в месте, где происходит отправка.

2024-12-06 01:22 UTC, bulbetski commented on internal/agent/agent.go
> +	resp, err := a.Send(metric, updateURI)
Ну и ничего страшного, я считаю. Очень редко есть профит строчки кода экономить

2024-12-07 20:27 UTC, renatus-cartesius commented on internal/agent/agent.go
> +	resp, err := a.Send(metric, updateURI)
В целом ок, в таком случае(два метода вместо одного) мы хотя бы сможем сразу задетализировать каждый по своему, а так бы пришлось все равно их разделять. Переделал

2024-12-07 23:16 UTC, renatus-cartesius commented on internal/agent/agent.go
> +			close(a.reportCh)
> Вообще схема в целом такая, не знаю ответит ли это на твой вопрос. Какая-то сущность отправляет джобы (как угодно, с какой угодной периодичностью) в канал, этот канал слушается твоим воркер пулом.
> 
> Канал надо закрыть в месте, где происходит отправка.

Схему я понимаю, вопрос о том, как понять переодической\временной сущности(в данном случае сущностью у нас является a.Report(), т.к. вызывается из-за тикера), что канал надо закрыть? Если я, к примеру, закрою агент по контексту, то a.Report() в select не успеет выполниться, чтобы закрыть канал.

Поэтому, я считаю, что все таки канал надо закрывать в Serve, т.к. он у нас является инциатором отправки в канал(в нем вызывается a.Report(), который является прямым отправителем). То есть, я без проблем могу весь код a.Report() перенести в select метода a.Serve(), что сделает a.Serve() отправителем и по сути будет достаточным для выполнения паттерна "отправитель закрывает канал"

2024-12-10 12:47 UTC, bulbetski approved these changes
Всё круто

2024-12-10 14:48 UTC, merged