Iter9
renatus-cartesius/metricserv pull request #9
Opened 2024-10-31 20:54 UTC by renatus-cartesius

2024-11-06 23:54 UTC, bulbetski reviewed
В целом мр хороший. Большая часть замечаний по код стайлу, но есть и парочка критических моментов, например с необработанными ошибками и пропущенными return'aми

2024-11-06 23:54 UTC, bulbetski commented on cmd/agent/main.go
> +	logger.Initialize(*agentLogLevel)
Стоит обработать ошибку инициализации логера.

2024-11-06 23:54 UTC, bulbetski commented on cmd/agent/main.go
>  	agent := agent.NewAgent(*reportInterval, *pollInterval, "http://"+*srvAddress, &monitor.MemMonitor{}, exitCh)
Тут мы разыменовываем кучу указателей -- это место, которое потенциально может привести к панике. Не то, чтобы так не делают, просто хорошей практикой было бы передать в функцию переменные по значению.  В комменте к флагам опишу, как можно отрефакторить, чтобы это стало возможным.

2024-11-06 23:54 UTC, bulbetski commented on cmd/agent/main.go
> +	agentLogLevel := flag.String("l", "INFO", "logging level")
Чтобы agentLogLevel у нас не был указателем вместо flag.String можно использовать flag.StringVar

Тогда можно заранее определить переменную и записать в нее значение флага
```
var agentLogLevel
flag.StringVar(&agentLogLevel, "l", "INFO", "logging level")
```
Соответственно в дальнейшем не придется разыменовывать указатель при передаче аргумента в функцию.
Это стоит сделать для всех флагов и после всех вызовов flag.*** нужно не забыть
`flag.Parse()`

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +	// fmt.Println(testStorage)
Нужны ли эти комментарии? Если нет, то лучше убрать

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +	logger.Initialize(*serverLogLevel)
Обработка ошибки

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		*saveInterval, _ = strconv.Atoi(envSaveInterval)
Обработка ошибки.
Так же стоит обрабатывать ошибку не через panic(err), а через `log.Fatal(err)`. Таким образом и приложение без паники завершим, и ошибку залогируем

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +	serverLogLevel := flag.String("l", "INFO", "logging level")
С флагами можно сделать то же, что я описал в комментах к main.go агента

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		memStorage.Load()
Не обработали ошибку

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +					memStorage.Save()
Не обработали ошибку. Стоит её залогировать

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
>  	})
Красиво было бы вынести всё это дело в отдельную функцию, чтобы оставить main() функцию чистой

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		*saveInterval, _ = strconv.Atoi(envSaveInterval)
на самом деле всё, что касается env значений и переменных для конфигурации твоего сервера, можно вынести в отдельную конфиг структуру

По типу
```
type Config struct {
    ServerAddress  string
    LogLevel       string
    SavePath       string
    SaveInterval   int
    RestoreStorage bool
}


func loadConfig() (*Config, error) {
    config := &Config{}
    flag.StringVar(&config.LogLevel, "l", config.LogLevel, "logging level")
    // остальные флаги
    flag.Parse()
    
    // остальной код
    return config, nil
}
```

```
func main() {
    config, err := loadConfig()
    if err != nil {
        log.Fatalf("Failed to load config: %v", err)
    }
        
    err = logger.Initialize(config.LogLevel)
    if err != nil {
        log.Fatal(err)
    }
}
```
Это просто приятное улучшение, не влияющие на функционал.

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		signal.Notify(sig, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
sig достаточно определить 1 раз перед всеми его вызовами, чтобы не дублировать код

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +			if shutdownCtx.Err() == context.DeadlineExceeded {
Ошибки лучше сравнивать через errors.Is(), потому что == требует полного соответствия, в то время как errors.Is() позволяет проверить, является ли ошибка определённым типом, даже если она обернута.

```
var ErrNotFound = errors.New("not found")
err := fmt.Errorf("error: %w", ErrNotFound) 

if errors.Is(err, ErrNotFound) {
    fmt.Println("resourse is not found")
}
```

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		shutdownCtx, shutdownCancel := context.WithTimeout(serverCtx, 30*time.Second)
Хорошей практикой является написание defer после создание контекста с cancel функцией.

```
shutdownCtx, shutdownCancel := context.WithTimeout(serverCtx, 30*time.Second)
defer shutdownCancel()
```

 В таком случае мы и уверены в том, что контекст завершится корректно или будет помечен как DeadlineExceeded (не надо дальше глазами букавы искать)

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +	serverCtx, serverStopCtx := context.WithCancel(context.Background())
Хорошей практикой является написание defer после создание контекста с cancel функцией.

в комменте с другим контекстом написал, почему

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		panic(err)
фатальный лог вместо паники

2024-11-06 23:54 UTC, bulbetski commented on cmd/server/main.go
> +		panic(err)
фатальный лог вместо паники

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
>  	pollTicker := time.NewTicker(time.Duration(a.pollInterval) * time.Second)
после тикеров стоит добавить defer reportTicker.Stop() и defer pollTicker.Stop()

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
> +	*metric.Delta = 1
В этом месте это ок, т.к. заранее инициализировал Delta, но если бы забыл, была бы паника. Для структуры Metric можно сделать SetDelta метод.

Например вот так
```
func (m *Metric) SetDelta(delta int64) {
	m.Delta = &delta
}
```

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
> +	url := fmt.Sprintf("%s/update", a.serverURL)
можно вынести /update в константу

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
> +		)
стоит завершить функцию return'ом в случае ошибки, чтобы мы не пошли дальше с nil запросом (req)

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
> +	}
Лучше закрывать тело запроса в defer'е. Так мы продолжим выполнение нашей функции (например твой дебаг лог не выведется, если будет ошибка закрытия тела)

```
	defer func() {
		if closeErr := res.Body.Close(); closeErr != nil {
			logger.Log.Error("error on closing response body", zap.Error(closeErr))
		}
	}()
```
можно упростить до
```
defer res.Body.Close()
```
По практике вряд ли ошибка произойдет)

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
> +		}
Кодирование метрики в JSON с проверкой на ошибку — это правильно.
Однако в случае ошибки лучше логировать сам объект метрики, а не буфер JSON, который еще не заполнен.

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
> +		}
Можно залогировать metric.ID

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
>  		}
Ошибка при создании запроса: хороший лог, но функция должна завершаться, так как req == nil. В конце добавить return.

Так же сначала обрабатываем ошибку, потом делаем `req.Header.Set("Content-Type", "application/json")` в случае успеха

2024-11-06 23:54 UTC, bulbetski commented on internal/agent/agent.go
>  		res.Body.Close()
лучше использовать defer для закрытия тела ответа

2024-11-06 23:54 UTC, bulbetski commented on internal/logger/logger.go
> +package logger
Хорошо написано. Очень тяжело прикопаться!

2024-11-06 23:54 UTC, bulbetski commented on internal/metrics/counter.go
> +		Type:  "counter",
"counter" может быть константой, например, `TypeCounter`, для единообразия в коде

2024-11-06 23:54 UTC, bulbetski commented on internal/metrics/gauge.go
> +		Type:  "gauge",
"gauge" может быть константой, например, `TypeGauge`, для единообразия в коде

2024-11-06 23:54 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
вместо InternalServerError лучше использовать StatusBadRequest, если тело запроса некорректно

2024-11-06 23:54 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		return
Здесь лучше обрабатывать ошибку при `ParseInt` и `ParseFloat`, так как неправильное значение может привести к панике.

2024-11-06 23:54 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
Как и в GetValueJSON, здесь лучше использовать StatusBadRequest для некорректного запроса.

2024-11-06 23:54 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +	}
Полезная проверка, но лучше логировать недопустимый тип для отладки.

2024-11-06 23:54 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +			// }
похоже, что лишний коммент

2024-11-06 23:54 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +			// }
лишний коммент

2024-11-06 23:54 UTC, bulbetski commented on internal/server/middlewares/middlewares.go
> +	gw.Header().Get("Content-Type")
Вызов `gw.Header().Get("Content-Type")` здесь ничего не делает, можно удалить.

2024-11-06 23:54 UTC, bulbetski commented on internal/server/middlewares/middlewares.go
> +			w.Header().Add("Content-Encoding", "gzip")
Это валидно, но можно использовать `Set`, чтобы исключить дублирование.

2024-11-06 23:54 UTC, bulbetski commented on internal/storage/storage.go
> +	metrics := s.Metrics
Здесь переменная `metrics` указывает на ту же карту, что и `s.Metrics`
В Go, когда функция возвращает map, это не копия данных, а ссылка на оригинальную map.
map (как и slice) в Go передаются по ссылке, даже если они возвращаются из функции

2024-11-06 23:54 UTC, bulbetski commented on internal/storage/storage.go
> +		panic(err)
Здесь панику лучше заменить на ошибку. Вообще нигде не стоит использовать панику, т.к. она может прервать выполнение программы

2024-11-06 23:54 UTC, bulbetski commented on internal/utils/utils.go
> +		logger.Log.Fatal(
logger.Log.Fatal завершает выполнение программы, что может быть нежелательно, особенно если ошибка закрытия файла не является критичной. Обычно ошибки закрытия файла логируют с уровнем Error

2024-11-07 22:14 UTC, renatus-cartesius commented
@bulbetski спасибо большое, очень интересное и детальное ревью)

2024-11-08 00:22 UTC, bulbetski commented
Не резолвь в следующий раз комментарии плиз. Я сам порезолвлю, если увижу, что ты исправил, так удобнее ревьюить

2024-11-08 00:32 UTC, bulbetski requested changes

2024-11-08 00:32 UTC, bulbetski commented on cmd/server/config/config.go
> +		config.SaveInterval, _ = strconv.Atoi(envSaveInterval)
обработка ошибок

2024-11-08 00:32 UTC, bulbetski commented on cmd/server/config/config.go
> +		config.RestoreStorage, _ = strconv.ParseBool(envRestoreStorage)
обработка ошибок

2024-11-08 00:32 UTC, bulbetski commented on cmd/server/main.go
>  		memStorage.Load()
Не обработали ошибку [2], а коммент порезолвлен)

2024-11-08 00:32 UTC, bulbetski commented on cmd/server/main.go
> +		saveTicker := time.NewTicker(time.Duration(config.SaveInterval) * time.Second)
нужно добавить defer на остановку тикера

2024-11-08 00:32 UTC, bulbetski commented on cmd/server/main.go
> +						log.Fatalln(err)
Фатальная ли это ошибка?

2024-11-08 00:32 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		logger.Log.Info(
Это лучше сделать не инфо логом, а Warn или Error

2024-11-08 00:32 UTC, bulbetski commented on internal/server/handlers/handlers.go
> +		}
не хотим ли мы делать return после каждой ошибки кейсах?

2024-11-08 00:32 UTC, bulbetski commented on cmd/agent/config/config.go
> +			panic(err)
паника вместо ошибка

2024-11-08 00:32 UTC, bulbetski commented on cmd/agent/config/config.go
> +			panic(err)
паника вместо ошибка

2024-11-08 00:32 UTC, bulbetski commented on cmd/agent/config/config.go
> +func LoadConfig() (*Config, error) {
Получилось как раз то, что хотел. Но давай еще для красоты сделаем как-то так

Сначала распарсим все флаги, а потом по очереди сделаем все наши env проверки.
```
	flag.StringVar(&config.SrvAddress, "a", "localhost:8080", "address to metrics server")
	flag.IntVar(&config.ReportInterval, "r", 10, "interval for reporting metrics to server")
	flag.IntVar(&config.PollInterval, "p", 2, "interval for polling to server")
	flag.StringVar(&config.AgentLogLevel, "l", "INFO", "logging level")

	// Parse flag values
	flag.Parse()
```

То же самое можно сделать для второго конфига

2024-11-09 23:50 UTC, renatus-cartesius commented
@bulbetski вроде бы все пофиксил. Единственное, в чем случился затык (можно увидеть по количество форс пушев и ребилдов), так это в объединении двух каналов для терминации в один. Почему-то, при вынесении инициализации канала, автотесты сервера зависают на этапе работы с сервером (https://github.com/renatus-cartesius/metricserv/actions/runs/11760203891/job/32760498411), при чем локально все работает как надо. Я не знаю детального утроства раннеров, но возможно такова специфика их работы или же в коде некорректо работаю с один каналом в двух местах. 

Вообщем пока оставил реализацию с двумя каналами для прерывания

2024-11-11 08:40 UTC, bulbetski commented on internal/agent/agent.go
> +		value, _ := strconv.ParseFloat(v, 64)
не обрабатываем ошибку

2024-11-11 11:58 UTC, bulbetski commented
Мр изначально был неплох, но хромал по код стайлу и обработке ошибок. После исправлений стало небо и земля -- хороший продакшн-реди код. Молодец

2024-11-11 11:59 UTC, bulbetski approved these changes

2024-11-11 12:01 UTC, merged